#!/usr/bin/env node
/**
 * Sync dev-ports.json → Docker Compose env + server/.env (DB host port only).
 * Dev only — production overrides DB_* in server/.env on the server.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const ports = JSON.parse(fs.readFileSync(path.join(ROOT, 'dev-ports.json'), 'utf8'));

const dbPort = Number(ports.db);
const dbUser = 'postgres';
const dbPassword = 'mes_dev_123';
const dbName = 'mes_prototype';

const dockerEnv = `# Generated by scripts/sync-dev-env.mjs — edit dev-ports.json instead
MES_DB_PORT=${dbPort}
MES_DB_USER=${dbUser}
MES_DB_PASSWORD=${dbPassword}
MES_DB_NAME=${dbName}
`;
fs.writeFileSync(path.join(ROOT, '.env.docker'), dockerEnv);

const serverEnvPath = path.join(ROOT, 'server', '.env');
if (fs.existsSync(serverEnvPath)) {
  let content = fs.readFileSync(serverEnvPath, 'utf8');
  const updates = {
    DATABASE_URL: `postgresql://${dbUser}:${dbPassword}@localhost:${dbPort}/${dbName}`,
    DB_HOST: 'localhost',
    DB_PORT: String(dbPort),
    DB_NAME: dbName,
    DB_USER: dbUser,
    DB_PASSWORD: dbPassword,
  };
  for (const [key, value] of Object.entries(updates)) {
    const re = new RegExp(`^${key}=.*$`, 'm');
    const line = `${key}=${value}`;
    content = re.test(content) ? content.replace(re, line) : `${content.replace(/\s*$/, '\n')}${line}\n`;
  }
  fs.writeFileSync(serverEnvPath, content);
}

console.log(
  `Dev ports synced: API ${ports.api}, UI ${ports.ui}, DB ${dbPort} (see dev-ports.json)`
);
