#!/usr/bin/env node
/**
 * Sync dev-ports.json → Docker Compose env + server/.env (DB host port only).
 * Dev only — production overrides DB_* in server/.env on the server.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const ports = JSON.parse(fs.readFileSync(path.join(ROOT, 'dev-ports.json'), 'utf8'));

const dbPort = Number(ports.db);
const dbUser = 'postgres';
const dbPassword = 'mes_dev_123';
const dbName = 'mes_prototype';

const dockerEnvPath = path.join(ROOT, '.env.docker');
const examplePath = path.join(ROOT, '.env.docker.example');
if (!fs.existsSync(dockerEnvPath) && fs.existsSync(examplePath)) {
  fs.copyFileSync(examplePath, dockerEnvPath);
  console.log('Created .env.docker from .env.docker.example');
}

const dbLines = {
  MES_DB_PORT: String(dbPort),
  MES_DB_USER: dbUser,
  MES_DB_PASSWORD: dbPassword,
  MES_DB_NAME: dbName,
};

const dockerPortLines = {
  MES_WEB_PORT: '6001',
  MES_API_PORT: '6000',
  MES_API_HOST_PORT: '6002',
  CORS_ORIGINS: 'http://localhost:6001,http://localhost:6002',
};

const optionalDefaults = {
  JWT_SECRET: 'mes-docker-local-dev-jwt-secret-min-32-chars',
  MES_AUTO_SEED: '1',
};

let dockerContent = fs.existsSync(dockerEnvPath)
  ? fs.readFileSync(dockerEnvPath, 'utf8')
  : `# Generated by scripts/sync-dev-env.mjs — edit dev-ports.json for DB port\n`;

function upsertEnvLine(content, key, value) {
  const re = new RegExp(`^${key}=.*$`, 'm');
  const line = `${key}=${value}`;
  return re.test(content) ? content.replace(re, line) : `${content.replace(/\s*$/, '\n')}${line}\n`;
}

for (const [key, value] of Object.entries(dbLines)) {
  dockerContent = upsertEnvLine(dockerContent, key, value);
}

for (const [key, value] of Object.entries(dockerPortLines)) {
  dockerContent = upsertEnvLine(dockerContent, key, value);
}

for (const [key, value] of Object.entries(optionalDefaults)) {
  const re = new RegExp(`^${key}=`, 'm');
  if (!re.test(dockerContent)) {
    dockerContent = upsertEnvLine(dockerContent, key, value);
  }
}

fs.writeFileSync(dockerEnvPath, dockerContent);

const serverEnvPath = path.join(ROOT, 'server', '.env');
if (fs.existsSync(serverEnvPath)) {
  let content = fs.readFileSync(serverEnvPath, 'utf8');
  const updates = {
    DATABASE_URL: `postgresql://${dbUser}:${dbPassword}@localhost:${dbPort}/${dbName}`,
    DB_HOST: 'localhost',
    DB_PORT: String(dbPort),
    DB_NAME: dbName,
    DB_USER: dbUser,
    DB_PASSWORD: dbPassword,
  };
  for (const [key, value] of Object.entries(updates)) {
    const re = new RegExp(`^${key}=.*$`, 'm');
    const line = `${key}=${value}`;
    content = re.test(content) ? content.replace(re, line) : `${content.replace(/\s*$/, '\n')}${line}\n`;
  }
  fs.writeFileSync(serverEnvPath, content);
}

console.log(
  `Dev ports synced: API ${ports.api}, UI ${ports.ui}, DB ${dbPort} (see dev-ports.json)`
);
